###################################################################################
#                                                                                 #
#  ________________________  ________________________ _                        _  #
# |                        |             |             \          /\          /   #
# |                                      |              \        /  \        /    #
# |                                      |               \      /    \      /     #
# |                                      |                \    /      \    /      #
# |                                      |                 \  /        \  /       #
# |________________________              |                  \/          \/        #
#                                                                                 #
#                                 CREATED BY JON                                  #
###################################################################################

#WORLD INFO
gameWorldFolderPath: "server/myWorldFolder"
redWoolLocation: ""
blueWoolLocation: ""

#LOBBY
lobbyWorldFolderPath: "server/lobbyWorldFolder"
lobbyCountdown: 10

#TEAMS
redSpawnLocations:
 - ""

 blueSpawnLocations:
 - ""

#PLAYER REQUIREMENTS
playersToStart: 2
playerLimit: 4

#COINS
coinsPerKill: 5
coinsPerCoarseDirt: 5

#CHANCES - (PERCENTAGE)
coinsPercentCoarseDirt: 25

#PRICES (NO SPACES. ADD : FOR PRICE AFTER ITEM, DEFAULT PRICE WILL BE 100 IF NOT SPECIFIED)
shopItems:
 - "barrier:*:0"
 - "stone_spade:100:2"
 - "iron_spade:250:4"
 - "diamond_spade:500:6"
 - "barrier:*:0"

#GAME RULES (ALL TIMES ARE IN SECONDS)
woolLimit: 2
deathFreezeTime: 5

#MESSAGES
woolTaken: "{teamColor} wool has been taken!"
woolDropped: "{woolColor}"
woolCaptured: "{woolColor} has been captured!"

#SCOREBOARD
scoreboard:
 - "&cYOUR TITLE"
 - "Team"
 - "{teamColor}"
 - "Wool"
 - "{woolStatus}"
 - "Wools Captured"
 - "{redCaptured}/{blueCaptured}"