# BUNGEEMODE
bungeeMode: true

# GAME WORLD INFO
game:
 worldName: "gameWorld"
 worldFolderPath: "server/gameWorld"
 redWoolLocation: ""
 blueWoolLocation: ""

# LOBBY
lobby:
 worldName: "lobby"
 worldFolderPath: "server/lobby"
 spawnLocation: "lobby,x,y,z,y,p"
 countdown: 10

 # TIMES (IN SECONDS)
time:
 dirtRegen: 900

 # REGIONS
region:
coarseDirt: # region selection
 - "gameWorld,x,y,z"
 - "gameWorld,x1,y1,z1"
redWoolCapture: # region selection
 - "gameWorld,x,y,z"
 - "gameWorld,x1,y1,z1"
blueWoolCapture: # region selection
 - "gameWorld,x,y,z"
 - "gameWorld,x1,y1,z1"

# SPAWN CHANCE
coarseDirtChance: 10

# TEAMS
spawnLocations:
 redTeam:
  - ""
 blueTeam:
  - ""

# PLAYER REQUIREMENTS (toStart = players needed to start | limit = maxPlayers allowed.)
players:
 toStart: 2
 limit: 4

# COINS
coins:
 perKill: 45
 perCoarseDirt: 35
 capture: 100

# CHANCES - (%PERCENTAGE%)
chances:
 coinsCoarseDirt: 25

# PRICES (ITEM:PRICE:INV_SLOT)
shopItems:
 - "barrier:*:0"
 - "stone_spade:100:2"
 - "iron_spade:250:4"
 - "diamond_spade:500:6"
 - "barrier:*:8"

# GAME RULES (ALL TIMES ARE IN SECONDS)
gameRules:
 woolLimit: 2
 deathFreezeTime: 5
 maxGameTime: 600
 timeLeftInterval: 60

# MESSAGES
messages:
 woolTaken: "{woolColor} &7wool has been taken!"
 woolDropped: "{woolColor} &7wool has been dropped!"
 woolCaptured: "{woolColor} &7has been captured!"
 timeLeft: "&7{time} &e{timeUnit} remaining!"

# SCOREBOARD
scoreboard:
 - "&cYOUR TITLE"
 - "Team"
 - "{teamColor}"
 - "&c"
 - "Wool"
 - "{woolStatus}"
 - "&d"
 - "Wools Captured"
 - "&c{redCaptured}&f/&9{blueCaptured}"