#BUNGEEMODE
bungeeMode: true

#GAME WORLD INFO
game:
 worldName: "gameWorld"
 worldFolderPath: "server/gameWorld"
 redWoolLocation: ""
 blueWoolLocation: ""

#LOBBY
lobby:
 worldName: "lobby"
 worldFolderPath: "server/lobby"
 spawnLocation: "lobby,x,y,z,y,p"
 countdown: 10

#TEAMS
spawnLocations:
 redTeam:
   - "gameWorld,x,y,z,y,p"
 blueTeam:
   - "gameWorld,x,y,z,y,p"

#PLAYER REQUIREMENTS (toStart = players needed to start | limit = maxPlayers allowed.)
players:
 toStart: 2
 limit: 4

#COINS
coins:
 perKill: 5
 perCoarseDirt: 5

#CHANCES - (%PERCENTAGE%)
chances:
 coinsCoarseDirt: 25

#PRICES (ITEM:PRICE:INV_SLOT)
shopItems: ["barrier:*:0", "stone_spade:100:2", "iron_spade:250:4", "diamond_spade:500:6", "barrier:*:0"]

#GAME RULES (ALL TIMES ARE IN SECONDS)
gameRules: {woolLimit: 2, deathFreezeTime: 5}

#MESSAGES
messages: {woolTaken: "{teamColor} wool has been taken!", woolDropped: "{woolColor}", woolCaptured: "{woolColor} has been captured!"}

#SCOREBOARD
scoreboard:
 - "&cYOUR TITLE"
 - "Team"
 - "{teamColor}"
 - "Wool"
 - "{woolStatus}"
 - "Wools Captured"
 - "{redCaptured}/{blueCaptured}"